import "./globals.css";

import { Bricolage_Grotesque, Roboto } from "next/font/google";

import { cn } from "@/lib/utils";

const fontHeading = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
  weight: "700",
});

const fontBody = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Learn with fun stories",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased", fontHeading.variable, fontBody.variable)}
      >
        {children}
      </body>
    </html>
  );
}
