import { Inter, Merienda } from "next/font/google";
import "./globals.css";
import { TokenProvider } from "@/context/TokenContext";
import { ClerkProvider } from "@clerk/nextjs";
import { Bricolage_Grotesque } from "next/font/google";
import { Space_Mono } from "next/font/google";
import { cn } from "@/lib/utils";

// import { TokenProvider } from "@/context/TokenContext";
const inter = Inter({ subsets: ["latin"] });

const fontHeading = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
  weight: "700",
});

const fontBody = Space_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
  weight: "700",
});

export const metadata = {
  title: "Learn with fun stories",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body
          className={cn("antialiased", fontHeading.variable, fontBody.variable)}
        >
          <TokenProvider>{children}</TokenProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
